spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-extension?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: 39.103.143.107
    port: 6379
    password: EDxD%KpLaf2qR@QM

#eureka:
#  client:
#    service-url:
#      defaultZone: http://39.108.136.207:8686/eureka/
#  instance:
#    prefer-ip-address: true
