spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: 121.43.33.238
    port: 6379
    password: 123456

logging:
  level:
    root: warn
    pers.fjl.server: debug
  file:
    path: log/blog-dev.log

ribbon:
  ReadTimeout: 600000000
  ConnectTimeout: 600000000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8686/eureka/
  instance:
    prefer-ip-address: true
